### PR TITLE
Send images from correct thread, fix Zeroconf announce

### PR DESCRIPTION
**Pull request by dnachbaur**

### CODE REVIEW

**Comment by dnachbaur** [comment]
FYI @eile

**Comment by rdumusc** [comment]
+1, Looks good. But note that when using the async send the socket is still technically written to from a (single) different thread. I suppose that Qt's warnings don't trigger in this case just because it's a boost thread and not a QThread.

**Comment by dnachbaur** [comment]
I didn't get warnings with asyncSend, but I'll doublecheck. Good point

**Comment by dnachbaur** [comment]
If the async sender has no QApplication, there is no warning. For Qt based async senders, we have to look into it again later. Right now, the only async sender is Equalizer-based applications, and there I noticed we have no event handling, so it's not useful right now anyways.

**Comment by rdumusc** [comment]
OK, good for me for now!

**Pull request merged**
