### PR TITLE
Port to Qt5

### PR DESCRIPTION
**Pull request by dnachbaur**

### CODE REVIEW

**Comment by dnachbaur** [comment]
retest this please

**Comment by dnachbaur** [comment]
retest this please

**Comment by dnachbaur** [comment]
retest this please

**Comment by dnachbaur** [comment]
retest this please

**Comment by dnachbaur** [comment]
retest this please

**Comment by rdumusc** [comment]
+1

**Comment by dnachbaur** [comment]
retest this please

**Comment by dnachbaur** [comment]
retest this please

**Pull request merged**
