### PR TITLE
DesktopStreamer: fix uncaught exception after #177

### PR DESCRIPTION
**Pull request by rdumusc**
Also report stream connection errors in the GUI instead of cerr.

### CODE REVIEW

**Review by dnachbaur — APPROVED** [review]

**Comment by rdumusc** [comment]
I forgot to adapt the OSX part, second commit coming soon

**Comment by rdumusc** [comment]
New commit added for the OSX version

**Comment by dnachbaur** [comment]
+1

**Comment by rdumusc** [comment]
retest this please

**Pull request merged**
