### PR TITLE
Fix receiving of uncompressed tiles

### PR DESCRIPTION
**Pull request by dnachbaur**

### CODE REVIEW

**Review by rdumusc — APPROVED** [review]
Ouch, good catch! Would you mind adding a test for uncompressed streaming too?

**Comment by rdumusc** [comment]
And there should be a log entry for 1.0.1 too, let me merge my PR first...

**Comment by dnachbaur** [comment]
Yes, I was waiting for your PR to update the changelog.

**Comment by dnachbaur** [comment]
Updated

**Comment by dnachbaur** [comment]
retest this please

**Comment by dnachbaur** [comment]
retest this please

**Pull request merged**
