### PR TITLE
Fix CPack config. Update default hostname for Geneva setup.

### PR DESCRIPTION
**Pull request by rdumusc**

### CODE REVIEW

**Comment by dnachbaur** [comment]
+1

**Comment by rdumusc** [comment]
Updated to automatically configure the OS X bundle file.
Packages for OS X + Ubuntu are ready, waiting for Jenkins and merging #12 before this one.
Once all the code is merged, I will create the release / tag and upload the binaries.

**Comment by dnachbaur** [comment]
retest this please

**Comment by rdumusc** [comment]
retest this please

**Comment by rdumusc** [comment]
retest this please

**Pull request merged**
