### PR TITLE
Fixed unit test deadlock due to incorrect execption handling

### PR DESCRIPTION
**Pull request by rdumusc**
This bug was introduced in #177 and could result in the global QThreadPool threads being locked forever.

### CODE REVIEW

**Review by dnachbaur — APPROVED** [review]

**Comment by rdumusc** [comment]
damn, still not fixed..!

**Comment by rdumusc** [comment]
retest this please

**Comment by rdumusc** [comment]
I'm merging because it already improves the situation (and #180 refuses to build without this). But the previous failure should not be ignored: https://bbpcode.epfl.ch/ci/job/oss.Deflect.github/405/build_type=Release,platform=cscsviz-vm/console

**Comment by rdumusc** [comment]
for the record, the remaining test failures are mostly due to concurrent calls to BOOST_CHECK

**Pull request merged**
